name: test

on:
  pull_request:
  push:

jobs:
  github-labeler:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v1
      -
        name: Labeler (test)
        uses: ./
        with:
          yaml_file: .res/labels.update.yml
          skip_delete: true
          dry_run: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Labeler (exclude part 1)
        uses: ./
        with:
          yaml_file: .res/labels.exclude1.yml
          dry_run: true
          exclude: "['d*', 'enhancement', '*fix']"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Labeler (exclude part 2)
        uses: ./
        with:
          yaml_file: .res/labels.exclude2.yml
          dry_run: true
          exclude: '*fix'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
