name: test

on:
  pull_request:
  push:

jobs:
  github-labeler:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v1
      -
        name: Labeler (update)
        uses: ./
        with:
          yaml_file: .res/labels.test.yml
          skip_delete: true
          dry_run: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Labeler (revert)
        uses: ./
        with:
          yaml_file: .res/samples/original.yml
          skip_delete: false
          dry_run: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
